import type { AIDifficulty } from './types';

export const AI_SCRIPTS: Record<string, Record<AIDifficulty, string>> = {
  COMBAT: {
    easy: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `IF MY_ENERGY < 18 THEN`,
      `  STOP`,
      `  WAIT 2`,
      `ELSE`,
      `  SET fovDirection = fovDirection + 0.18`,
      `END`,
      `IF MY_ENERGY > 17 AND VISIBLE_ENEMY_COUNT > 0 THEN`,
      `  SET _SYS_ORBIT_R = "OFF"`,
      `  SET _SYS_STRAFE = 0`,
      `  SET dx = NEAREST_VISIBLE_X - POSITION_X`,
      `  SET dy = NEAREST_VISIBLE_Y - POSITION_Y`,
      `  SET rotation = ATAN2(dy, dx)`,
      `  SET fovDirection = rotation`,
      `  SET lockVision = 1`,
      `  SET dist = SQRT((dx * dx) + (dy * dy))`,
      `  IF MY_ENERGY > 28 AND dist <= 300 THEN`,
      `    FIRE`,
      `  END`,
      `  IF MY_ENERGY > 24 AND dist > 180 THEN`,
      `    MOVE`,
      `  ELSE`,
      `    SET _SYS_STRAFE = 1`,
      `    IF MY_ENERGY > 24 THEN`,
      `      MOVE`,
      `    END`,
      `  END`,
      `ELSE`,
      `  SET _SYS_STRAFE = 0`,
      `  SET _SYS_ORBIT_R = "OFF"`,
      `  SET rotation = rotation + 0.12`,
      `  IF MY_ENERGY > 35 THEN`,
      `    MOVE`,
      `  END`,
      `END`,
    ].join('\n'),
    medium: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `IF MY_ENERGY < 22 THEN`,
      `  STOP`,
      `  WAIT 2`,
      `ELSE`,
      `  SET fovDirection = fovDirection + 0.2`,
      `END`,
      `IF MY_ENERGY > 21 AND VISIBLE_ENEMY_COUNT > 0 THEN`,
      `  SET _SYS_ORBIT_R = "OFF"`,
      `  SET dx = NEAREST_VISIBLE_X - POSITION_X`,
      `  SET dy = NEAREST_VISIBLE_Y - POSITION_Y`,
      `  SET rotation = ATAN2(dy, dx)`,
      `  SET fovDirection = rotation`,
      `  SET lockVision = 1`,
      `  SET dist = SQRT((dx * dx) + (dy * dy))`,
      `  IF MY_ENERGY > 65 AND dist <= 280 THEN`,
      `    BURST_FIRE`,
      `  ELSE`,
      `    IF MY_ENERGY > 30 AND dist <= 330 THEN`,
      `      FIRE`,
      `    END`,
      `  END`,
      `  IF MY_ENERGY > 35 AND dist > 240 THEN`,
      `    SET _SYS_STRAFE = 0`,
      `    MOVE`,
      `  ELSE`,
      `    IF dist < 120 THEN`,
      `      SET _SYS_STRAFE = 0`,
      `      IF MY_ENERGY > 28 THEN`,
      `        BACKUP`,
      `      END`,
      `    ELSE`,
      `      SET _SYS_STRAFE = 1`,
      `      IF MY_ENERGY > 32 THEN`,
      `        MOVE`,
      `      END`,
      `    END`,
      `  END`,
      `ELSE`,
      `  SET _SYS_STRAFE = 0`,
      `  SET _SYS_ORBIT_R = "OFF"`,
      `  SET rotation = rotation + 0.2`,
      `  IF MY_ENERGY > 40 THEN`,
      `    MOVE`,
      `  END`,
      `END`,
    ].join('\n'),
    hard: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `  SET mineCd = 0`,
      `  SET shieldCd = 0`,
      `END`,
      `IF mineCd > 0 THEN`,
      `  SET mineCd = mineCd - 1`,
      `END`,
      `IF shieldCd > 0 THEN`,
      `  SET shieldCd = shieldCd - 1`,
      `END`,
      `IF MY_ENERGY < 25 THEN`,
      `  STOP`,
      `  WAIT 3`,
      `ELSE`,
      `  SET fovDirection = fovDirection + 0.24`,
      `END`,
      `IF MY_ENERGY > 24 AND VISIBLE_ENEMY_COUNT > 0 THEN`,
      `  SET _SYS_ORBIT_R = "OFF"`,
      `  SET dx = NEAREST_VISIBLE_X - POSITION_X`,
      `  SET dy = NEAREST_VISIBLE_Y - POSITION_Y`,
      `  SET dist = SQRT((dx * dx) + (dy * dy))`,
      `  SET aim = ATAN2(dy, dx)`,
      `  SET rotation = aim`,
      `  SET fovDirection = aim`,
      `  SET lockVision = 1`,
      `  IF MY_ENERGY > 78 AND dist <= 260 THEN`,
      `    BURST_FIRE`,
      `  ELSE`,
      `    IF MY_ENERGY > 34 AND dist <= 340 THEN`,
      `      FIRE`,
      `    END`,
      `  END`,
      `  IF MY_ENERGY > 82 THEN`,
      `    IF mineCd <= 0 THEN`,
      `      IF dist < 95 THEN`,
      `        MINE`,
      `        SET mineCd = 30`,
      `      END`,
      `    END`,
      `  END`,
      `  IF dist > 260 THEN`,
      `    SET _SYS_STRAFE = 0`,
      `    IF MY_ENERGY > 45 THEN`,
      `      MOVE_FAST`,
      `    ELSE`,
      `      MOVE`,
      `    END`,
      `  ELSE`,
      `    IF dist < 130 THEN`,
      `      SET _SYS_STRAFE = 0`,
      `      IF MY_ENERGY > 30 THEN`,
      `        BACKUP`,
      `      END`,
      `    ELSE`,
      `      SET _SYS_STRAFE = -1`,
      `      IF MY_ENERGY > 36 THEN`,
      `        MOVE`,
      `      END`,
      `    END`,
      `  END`,
      `  IF MY_ENERGY > 88 THEN`,
      `    IF shieldCd <= 0 THEN`,
      `      IF dist < 120 THEN`,
      `        SHIELD`,
      `        SET shieldCd = 35`,
      `      END`,
      `    END`,
      `  END`,
      `ELSE`,
      `  SET _SYS_STRAFE = 0`,
      `  SET _SYS_ORBIT_R = "OFF"`,
      `  SET rotation = rotation + 0.24`,
      `  IF MY_ENERGY > 55 THEN`,
      `    MOVE_FAST`,
      `  ELSE`,
      `    IF MY_ENERGY > 35 THEN`,
      `      MOVE`,
      `    END`,
      `  END`,
      `END`,
    ].join('\n'),
  },

  CAPTURE_THE_FLAG: {
    easy: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SET fx = ENEMY_FLAG_X`,
      `SET fy = ENEMY_FLAG_Y`,
      `SET dx = fx - POSITION_X`,
      `SET dy = fy - POSITION_Y`,
      `SET rotation = ATAN2(dy, dx)`,
      `SET fdist = SQRT((dx * dx) + (dy * dy))`,
      `IF fdist > 50 THEN`,
      `  MOVE_FAST`,
      `ELSE`,
      `  SET bx = MY_FLAG_X`,
      `  SET by = MY_FLAG_Y`,
      `  SET hdx = bx - POSITION_X`,
      `  SET hdy = by - POSITION_Y`,
      `  SET rotation = ATAN2(hdy, hdx)`,
      `  MOVE_FAST`,
      `END`,
    ].join('\n'),
    medium: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SCAN`,
      `SET fx = ENEMY_FLAG_X`,
      `SET fy = ENEMY_FLAG_Y`,
      `SET dx = fx - POSITION_X`,
      `SET dy = fy - POSITION_Y`,
      `SET fdist = SQRT((dx * dx) + (dy * dy))`,
      `SET rotation = ATAN2(dy, dx)`,
      `IF VISIBLE_ENEMY_COUNT > 0 AND MY_ENERGY > 15 THEN`,
      `  SET rotation = ATAN2(NEAREST_VISIBLE_Y - POSITION_Y, NEAREST_VISIBLE_X - POSITION_X)`,
      `  SET fovDirection = rotation`,
      `  SET lockVision = 1`,
      `  FIRE`,
      `END`,
      `IF fdist > 50 THEN`,
      `  MOVE_FAST`,
      `ELSE`,
      `  SET bx = MY_FLAG_X`,
      `  SET by = MY_FLAG_Y`,
      `  SET hdx = bx - POSITION_X`,
      `  SET hdy = by - POSITION_Y`,
      `  SET rotation = ATAN2(hdy, hdx)`,
      `  SET hdist = SQRT((hdx * hdx) + (hdy * hdy))`,
      `  IF hdist > 30 THEN`,
      `    MOVE_FAST`,
      `  ELSE`,
      `    STOP`,
      `  END`,
      `END`,
    ].join('\n'),
    hard: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SCAN`,
      `SET fx = ENEMY_FLAG_X`,
      `SET fy = ENEMY_FLAG_Y`,
      `SET dx = fx - POSITION_X`,
      `SET dy = fy - POSITION_Y`,
      `SET fdist = SQRT((dx * dx) + (dy * dy))`,
      `SET rotation = ATAN2(dy, dx)`,
      `IF VISIBLE_ENEMY_COUNT > 0 THEN`,
      `  SET edx = NEAREST_VISIBLE_X - POSITION_X`,
      `  SET edy = NEAREST_VISIBLE_Y - POSITION_Y`,
      `  SET rotation = ATAN2(edy, edx)`,
      `  SET lockVision = 1`,
      `  IF MY_ENERGY > 20 THEN`,
      `    LEAD_FIRE`,
      `  END`,
      `  IF MY_ENERGY > 60 AND fdist < 200 THEN`,
      `    SHIELD`,
      `  END`,
      `END`,
      `IF fdist > 50 THEN`,
      `  MOVE_FAST`,
      `ELSE`,
      `  SET bx = MY_FLAG_X`,
      `  SET by = MY_FLAG_Y`,
      `  SET hdx = bx - POSITION_X`,
      `  SET hdy = by - POSITION_Y`,
      `  SET rotation = ATAN2(hdy, hdx)`,
      `  SET hdist = SQRT((hdx * hdx) + (hdy * hdy))`,
      `  IF MY_ENERGY > 60 AND hdist > 100 THEN`,
      `    SHIELD`,
      `  END`,
      `  IF hdist > 30 THEN`,
      `    MOVE_FAST`,
      `  ELSE`,
      `    STOP`,
      `  END`,
      `END`,
    ].join('\n'),
  },

  KING_OF_THE_HILL: {
    easy: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SET dx = 400 - POSITION_X`,
      `SET dy = 300 - POSITION_Y`,
      `SET rotation = ATAN2(dy, dx)`,
      `SET dist = SQRT((dx * dx) + (dy * dy))`,
      `IF dist > 80 THEN`,
      `  MOVE_FAST`,
      `ELSE`,
      `  STOP`,
      `END`,
    ].join('\n'),
    medium: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SCAN`,
      `SET dx = 400 - POSITION_X`,
      `SET dy = 300 - POSITION_Y`,
      `SET rotation = ATAN2(dy, dx)`,
      `SET dist = SQRT((dx * dx) + (dy * dy))`,
      `IF dist > 60 THEN`,
      `  MOVE_FAST`,
      `ELSE`,
      `  IF VISIBLE_ENEMY_COUNT > 0 AND MY_ENERGY > 15 THEN`,
      `    SET edx = NEAREST_VISIBLE_X - POSITION_X`,
      `    SET edy = NEAREST_VISIBLE_Y - POSITION_Y`,
      `    SET rotation = ATAN2(edy, edx)`,
      `    SET lockVision = 1`,
      `    BURST_FIRE`,
      `  END`,
      `  STOP`,
      `END`,
    ].join('\n'),
    hard: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SCAN`,
      `SET dx = 400 - POSITION_X`,
      `SET dy = 300 - POSITION_Y`,
      `SET rotation = ATAN2(dy, dx)`,
      `SET dist = SQRT((dx * dx) + (dy * dy))`,
      `IF VISIBLE_ENEMY_COUNT > 0 THEN`,
      `  SET edx = NEAREST_VISIBLE_X - POSITION_X`,
      `  SET edy = NEAREST_VISIBLE_Y - POSITION_Y`,
      `  SET rotation = ATAN2(edy, edx)`,
      `  SET lockVision = 1`,
      `  SET edist = SQRT((edx * edx) + (edy * edy))`,
      `  IF MY_ENERGY > 25 THEN`,
      `    LEAD_FIRE`,
      `  END`,
      `  IF MY_ENERGY > 60 AND edist < 150 THEN`,
      `    SHIELD`,
      `  END`,
      `  IF edist > 100 THEN`,
      `    MOVE_FAST`,
      `  ELSE`,
      `    BACKUP`,
      `  END`,
      `ELSE`,
      `  IF dist > 80 THEN`,
      `    MOVE_FAST`,
      `  ELSE`,
      `    STOP`,
      `  END`,
      `END`,
    ].join('\n'),
  },

  SURVIVAL: {
    easy: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SCAN`,
      `IF VISIBLE_ENEMY_COUNT > 0 THEN`,
      `  SET dx = NEAREST_VISIBLE_X - POSITION_X`,
      `  SET dy = NEAREST_VISIBLE_Y - POSITION_Y`,
      `  SET rotation = ATAN2(dy, dx)`,
      `  SET lockVision = 1`,
      `  SET dist = SQRT((dx * dx) + (dy * dy))`,
      `  IF dist <= 300 THEN`,
      `    FIRE`,
      `  END`,
      `  MOVE`,
      `ELSE`,
      `  SET rotation = rotation + 0.15`,
      `END`,
    ].join('\n'),
    medium: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SCAN`,
      `IF VISIBLE_ENEMY_COUNT > 0 THEN`,
      `  SET dx = NEAREST_VISIBLE_X - POSITION_X`,
      `  SET dy = NEAREST_VISIBLE_Y - POSITION_Y`,
      `  SET rotation = ATAN2(dy, dx)`,
      `  SET lockVision = 1`,
      `  SET dist = SQRT((dx * dx) + (dy * dy))`,
      `  IF MY_ENERGY > 20 AND dist <= 300 THEN`,
      `    BURST_FIRE`,
      `  END`,
      `  IF dist > 80 THEN`,
      `    MOVE_FAST`,
      `  ELSE`,
      `    BACKUP`,
      `  END`,
      `ELSE`,
      `  SET rotation = rotation + 0.15`,
      `  MOVE`,
      `END`,
    ].join('\n'),
    hard: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SCAN`,
      `IF VISIBLE_ENEMY_COUNT > 0 THEN`,
      `  SET dx = NEAREST_VISIBLE_X - POSITION_X`,
      `  SET dy = NEAREST_VISIBLE_Y - POSITION_Y`,
      `  SET rotation = ATAN2(dy, dx)`,
      `  SET lockVision = 1`,
      `  SET dist = SQRT((dx * dx) + (dy * dy))`,
      `  IF MY_ENERGY > 25 AND dist <= 300 THEN`,
      `    LEAD_FIRE`,
      `  END`,
      `  IF MY_ENERGY > 60 AND dist < 100 THEN`,
      `    SHIELD`,
      `  END`,
      `  IF dist > 120 THEN`,
      `    MOVE_FAST`,
      `  ELSE`,
      `    BACKUP`,
      `  END`,
      `ELSE`,
      `  SET rotation = rotation + 0.2`,
      `  MOVE`,
      `END`,
    ].join('\n'),
  },

  RACING: {
    easy: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `MOVE_FAST`,
    ].join('\n'),
    medium: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SCAN`,
      `IF CAN_SEE_OBSTACLE AND NEAREST_OBSTACLE_DISTANCE < 100 THEN`,
      `  SET rotation = rotation + 1.57`,
      `END`,
      `MOVE_FAST`,
    ].join('\n'),
    hard: [
      `IF NOT init THEN`,
      `  SET init = 1`,
      `END`,
      `SCAN`,
      `SET dx = 750 - POSITION_X`,
      `SET dy = 300 - POSITION_Y`,
      `SET targetAngle = ATAN2(dy, dx)`,
      `IF CAN_SEE_OBSTACLE AND NEAREST_OBSTACLE_DISTANCE < 120 THEN`,
      `  SET rotation = rotation + 1.57`,
      `ELSE`,
      `  SET rotation = targetAngle`,
      `END`,
      `MOVE_FAST`,
    ].join('\n'),
  },
};
