import type { SceneScript } from '../sceneScriptEngine';

export const ARRAY_SCRIPTS: Record<string, SceneScript> = {
  'arr-01': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'moveTo', x: 0.55, y: 0.35 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveTo', x: 0.65, y: 0.35 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveTo', x: 0.55, y: 0.55 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveTo', x: 0.65, y: 0.55 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveTo', x: 0.60, y: 0.45 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveTo', x: 0.75, y: 0.50 } },
    ],
  },
  'arr-02': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'arr-03': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'rotate', angle: -0.4 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'rotate', angle: 0.4 } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'rotate', angle: -0.4 } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'rotate', angle: 0.4 } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'arr-04': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  25, action: { type: 'idle' } },
    ],
  },
  'arr-05': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'moveTo', x: 0.55, y: 0.50 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveTo', x: 0.65, y: 0.50 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveTo', x: 0.55, y: 0.50 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'moveTo', x: 0.70, y: 0.50 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveTo', x: 0.75, y: 0.50 } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'arr-06': {
    loop: true,
    phases: [
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   9, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'arr-07': {
    loop: true,
    phases: [
      { ticks:  15, action: { type: 'moveTo', x: 0.55, y: 0.35 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.65, y: 0.35 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.55, y: 0.50 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.65, y: 0.50 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.55, y: 0.65 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.65, y: 0.65 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  15, action: { type: 'moveTo', x: 0.60, y: 0.50 } },
      { ticks:  12, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'burst' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'arr-08': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  20, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'arr-09': {
    loop: true,
    phases: [
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  15, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'arr-10': {
    loop: true,
    phases: [
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  18, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
};
