import type { SceneScript } from '../sceneScriptEngine';

export const CONDITIONAL_SCRIPTS: Record<string, SceneScript> = {
  'cond-01': {
    loop: true,
    phases: [
      { ticks:  45, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  70, action: { type: 'moveTo', x: 0.50, y: 0.50 } },
      { ticks:  35, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'cond-02': {
    loop: true,
    phases: [
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'rotate', angle: -0.6 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'rotate', angle: 0.6 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'rotate', angle: -0.6 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  15, action: { type: 'rotate', angle: 0.6 } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'idle' } },
    ],
  },
  'cond-03': {
    loop: true,
    phases: [
      { ticks:  40, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  20, action: { type: 'burst' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'cond-04': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveTo', x: 0.55, y: 0.50 } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'cond-05': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  12, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'idle' } },
    ],
  },
  'cond-06': {
    loop: true,
    phases: [
      { ticks:  50, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  50, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:   5, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'idle' } },
    ],
  },
  'cond-07': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'scan' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'fire' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'cond-08': {
    loop: true,
    phases: [
      { ticks:  40, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'cond-09': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  35, action: { type: 'moveTo', x: 0.65, y: 0.45 } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:   6, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'moveTo', x: 0.75, y: 0.50 } },
      { ticks:  35, action: { type: 'idle' } },
    ],
  },
  'cond-10': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:   8, action: { type: 'fire' } },
      { ticks:  40, action: { type: 'idle' } },
    ],
  },
};
