import type { SceneScript } from '../sceneScriptEngine';

export const RECURSION_SCRIPTS: Record<string, SceneScript> = {
  'rec-01': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  28, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'rec-02': {
    loop: true,
    phases: [
      { ticks:  30, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  30, action: { type: 'scan' } },
      { ticks:  28, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'rec-03': {
    loop: true,
    phases: [
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  22, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'rec-04': {
    loop: true,
    phases: [
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  34, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  34, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'rec-05': {
    loop: true,
    phases: [
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'rec-06': {
    loop: true,
    phases: [
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  24, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  34, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  34, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'rec-07': {
    loop: true,
    phases: [
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  25, action: { type: 'scan' } },
      { ticks:  20, action: { type: 'idle' } },
    ],
  },
  'rec-08': {
    loop: true,
    phases: [
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'rec-09': {
    loop: true,
    phases: [
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  16, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
  'rec-10': {
    loop: true,
    phases: [
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  22, action: { type: 'scan' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'right' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  14, action: { type: 'moveDir', dir: 'left' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:   4, action: { type: 'fire' } },
      { ticks:  10, action: { type: 'idle' } },
    ],
  },
};
